# Generated by Django 3.0.8 on 2020-07-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='accounts.Subject'),
        ),
    ]
