# Generated by Django 3.0.8 on 2020-07-30 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200728_0535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='takenQuizzes',
        ),
    ]
