# Generated by Django 3.0.8 on 2020-07-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='maxScore',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
