# Generated by Django 3.0.8 on 2020-07-30 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20200730_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='rating',
            field=models.IntegerField(blank=5, default=5),
        ),
    ]
