# Generated by Django 3.0.8 on 2020-07-30 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quiz_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='maxScore',
            field=models.IntegerField(),
        ),
    ]
