# Generated by Django 3.0.8 on 2020-07-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_takenquizzes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5, max_digits=2),
        ),
    ]
