# Generated by Django 3.0.8 on 2020-07-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20200730_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='takenquizzes',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
