# Generated by Django 3.0.8 on 2020-07-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20200730_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
